### ISSUE TITLE
user Auto login after register

### ISSUE THREAD

**Issue by Alwerdani** [mishbahr/django-users2#17]
Hello ,
when i set ``` USERS_AUTO_LOGIN_ON_ACTIVATION = True```  and  ``` USERS_VERIFY_EMAIL = False `` the user not automatically login after register .

**Comment by mishbahr** [comment]
I haven't used this functionality for a while! So haven't really tested with the latest version of django ..I'll look into this as soon as I can. In the mean time if you figure out the cause this issue ... pull requests are welcome. 

The issue is probably here: https://github.com/mishbahr/django-users2/blob/master/users/views.py#L144

Thank for raising the issue.

Regards

Mishbah

**Comment by Alwerdani** [comment]
Thanks for your interest , i add ``` settings.USERS_AUTO_LOGIN_AFTER_REGISTRATION ``` to make this functionality, you can see the changes on my pull request .

**Comment by mishbahr** [comment]
https://github.com/mishbahr/django-users2/pull/18
